#ifndef _STRUCTURES_H
#define _STRUCTURES_H

// File generated by PDBRipper ver 1.13 (http://www.ntinfo.biz)
// Bugreports : horsicq@gmail.com


enum std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Mref
{
    _FROZEN=255
};
enum _QUERY_TYPE_
{
    QUERY_INSERT=0,
    QUERY_DELETE=1
};
enum SQLINTERVAL
{
    SQL_IS_YEAR=1,
    SQL_IS_MONTH=2,
    SQL_IS_DAY=3,
    SQL_IS_HOUR=4,
    SQL_IS_MINUTE=5,
    SQL_IS_SECOND=6,
    SQL_IS_YEAR_TO_MONTH=7,
    SQL_IS_DAY_TO_HOUR=8,
    SQL_IS_DAY_TO_MINUTE=9,
    SQL_IS_DAY_TO_SECOND=10,
    SQL_IS_HOUR_TO_MINUTE=11,
    SQL_IS_HOUR_TO_SECOND=12,
    SQL_IS_MINUTE_TO_SECOND=13
};
enum STUB_PHASE
{
    STUB_UNMARSHAL=0,
    STUB_CALL_SERVER=1,
    STUB_MARSHAL=2,
    STUB_CALL_SERVER_NO_HRESULT=3
};
enum LATENCY_TIME
{
    LT_DONT_CARE=0,
    LT_LOWEST_LATENCY=1
};
enum FilterType
{
    FILTERSPECV4=1,
    FILTERSPECV6=2,
    FILTERSPECV6_FLOW=3,
    FILTERSPECV4_GPI=4,
    FILTERSPECV6_GPI=5,
    FILTERSPEC_END=6
};
enum PROXY_PHASE
{
    PROXY_CALCSIZE=0,
    PROXY_GETBUFFER=1,
    PROXY_MARSHAL=2,
    PROXY_SENDRECEIVE=3,
    PROXY_UNMARSHAL=4
};
enum XLAT_SIDE
{
    XLAT_SERVER=1,
    XLAT_CLIENT=2
};
enum _RPC_ASYNC_EVENT
{
    RpcCallComplete=0,
    RpcSendComplete=1,
    RpcReceiveComplete=2
};
enum std::_Tree<unsigned long,std::pair<unsigned long const ,ACCOUNT_INFO *>,std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Kfn,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Redbl
{
    _Red=0,
    _Black=1
};
enum _RPC_NOTIFICATION_TYPES
{
    RpcNotificationTypeNone=0,
    RpcNotificationTypeEvent=1,
    RpcNotificationTypeApc=2,
    RpcNotificationTypeIoc=3,
    RpcNotificationTypeHwnd=4,
    RpcNotificationTypeCallback=5
};
enum ADDRESS_MODE
{
    AddrMode1616=0,
    AddrMode1632=1,
    AddrModeReal=2,
    AddrModeFlat=3
};
enum SYM_TYPE
{
    SymNone=0,
    SymCoff=1,
    SymCv=2,
    SymPdb=3,
    SymExport=4,
    SymDeferred=5,
    SymSym=6
};
enum _IMAGEHLP_STATUS_REASON
{
    BindOutOfMemory=0,
    BindRvaToVaFailed=1,
    BindNoRoomInImage=2,
    BindImportModuleFailed=3,
    BindImportProcedureFailed=4,
    BindImportModule=5,
    BindImportProcedure=6,
    BindForwarder=7,
    BindForwarderNOT=8,
    BindImageModified=9,
    BindExpandFileHeaders=10,
    BindImageComplete=11,
    BindMismatchedSymbols=12,
    BindSymbolsNotUpdated=13
};
typedef union tagCY // Size=8
{
    struct
    {
        unsigned long Lo; // Size=4 Offset=0
        long Hi; // Size=4 Offset=4
    };
    __int64 int64; // Size=8 Offset=0
} *PtagCY;
typedef struct _FILETIME // Size=8
{
    unsigned long dwLowDateTime; // Size=4 Offset=0
    unsigned long dwHighDateTime; // Size=4 Offset=4
} FILETIME, *PFILETIME;
typedef struct _GUID // Size=16
{
    unsigned long Data1; // Size=4 Offset=0
    unsigned short Data2; // Size=2 Offset=4
    unsigned short Data3; // Size=2 Offset=6
    unsigned char Data4[8]; // Size=8 Offset=8
} GUID, *PGUID;
typedef struct tagBLOB // Size=8
{
    unsigned long cbSize; // Size=4 Offset=0
    unsigned char * pBlobData; // Size=4 Offset=4
} *PtagBLOB;
typedef struct tagCLIPDATA // Size=12
{
    unsigned long cbSize; // Size=4 Offset=0
    long ulClipFmt; // Size=4 Offset=4
    unsigned char * pClipData; // Size=4 Offset=8
} *PtagCLIPDATA;
typedef struct IStream // Size=4
{
} *PIStream;
typedef struct IStorage // Size=4
{
} *PIStorage;
typedef struct tagBSTRBLOB // Size=8
{
    unsigned long cbSize; // Size=4 Offset=0
    unsigned char * pData; // Size=4 Offset=4
} *PtagBSTRBLOB;
typedef struct tagCAUB // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    unsigned char * pElems; // Size=4 Offset=4
} *PtagCAUB;
typedef struct tagCAI // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    short * pElems; // Size=4 Offset=4
} *PtagCAI;
typedef struct tagCAUI // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    unsigned short * pElems; // Size=4 Offset=4
} *PtagCAUI;
typedef struct tagCABOOL // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    short * pElems; // Size=4 Offset=4
} *PtagCABOOL;
typedef struct tagCAL // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    long * pElems; // Size=4 Offset=4
} *PtagCAL;
typedef struct tagCAUL // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    unsigned long * pElems; // Size=4 Offset=4
} *PtagCAUL;
typedef struct tagCAFLT // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    float * pElems; // Size=4 Offset=4
} *PtagCAFLT;
typedef struct tagCASCODE // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    long * pElems; // Size=4 Offset=4
} *PtagCASCODE;
typedef struct tagCADBL // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    double * pElems; // Size=4 Offset=4
} *PtagCADBL;
typedef struct tagCADATE // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    double * pElems; // Size=4 Offset=4
} *PtagCADATE;
typedef struct tagCABSTR // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    unsigned short * * pElems; // Size=4 Offset=4
} *PtagCABSTR;
typedef struct tagCALPSTR // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    char * * pElems; // Size=4 Offset=4
} *PtagCALPSTR;
typedef struct tagCALPWSTR // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    unsigned short * * pElems; // Size=4 Offset=4
} *PtagCALPWSTR;
typedef struct in_addr::__unnamed::__unnamed // Size=4
{
    unsigned char s_b1; // Size=1 Offset=0
    unsigned char s_b2; // Size=1 Offset=1
    unsigned char s_b3; // Size=1 Offset=2
    unsigned char s_b4; // Size=1 Offset=3
} *Pin_addr::__unnamed::__unnamed;
typedef union _IN_ADDR_IPV4 // Size=4
{
    unsigned long Addr; // Size=4 Offset=0
    unsigned char AddrBytes[4]; // Size=4 Offset=0
} IN_ADDR_IPV4, *PIN_ADDR_IPV4;
typedef struct _IN_ADDR_IPV6 // Size=16
{
    unsigned char Addr[16]; // Size=16 Offset=0
} IN_ADDR_IPV6, *PIN_ADDR_IPV6;
typedef struct _flowspec // Size=32
{
    unsigned long TokenRate; // Size=4 Offset=0
    unsigned long TokenBucketSize; // Size=4 Offset=4
    unsigned long PeakBandwidth; // Size=4 Offset=8
    unsigned long Latency; // Size=4 Offset=12
    unsigned long DelayVariation; // Size=4 Offset=16
    unsigned long ServiceType; // Size=4 Offset=20
    unsigned long MaxSduSize; // Size=4 Offset=24
    unsigned long MinimumPolicedSize; // Size=4 Offset=28
} flowspec, *Pflowspec;
typedef struct QOS_OBJECT_HDR // Size=8
{
    unsigned long ObjectType; // Size=4 Offset=0
    unsigned long ObjectLength; // Size=4 Offset=4
} *PQOS_OBJECT_HDR;
typedef struct _AD_GENERAL_PARAMS // Size=20
{
    unsigned long IntServAwareHopCount; // Size=4 Offset=0
    unsigned long PathBandwidthEstimate; // Size=4 Offset=4
    unsigned long MinimumLatency; // Size=4 Offset=8
    unsigned long PathMTU; // Size=4 Offset=12
    unsigned long Flags; // Size=4 Offset=16
} AD_GENERAL_PARAMS, *PAD_GENERAL_PARAMS;
typedef struct _AD_GUARANTEED // Size=16
{
    unsigned long CTotal; // Size=4 Offset=0
    unsigned long DTotal; // Size=4 Offset=4
    unsigned long CSum; // Size=4 Offset=8
    unsigned long DSum; // Size=4 Offset=12
} AD_GUARANTEED, *PAD_GUARANTEED;
typedef struct _PARAM_BUFFER // Size=12
{
    unsigned long ParameterId; // Size=4 Offset=0
    unsigned long Length; // Size=4 Offset=4
    unsigned char Buffer[1]; // Size=1 Offset=8
} PARAM_BUFFER, *PPARAM_BUFFER;
typedef struct _WSABUF // Size=8
{
    unsigned long len; // Size=4 Offset=0
    char * buf; // Size=4 Offset=4
} WSABUF, *PWSABUF;
typedef struct _WSAPROTOCOLCHAIN // Size=32
{
    int ChainLen; // Size=4 Offset=0
    unsigned long ChainEntries[7]; // Size=28 Offset=4
} WSAPROTOCOLCHAIN, *PWSAPROTOCOLCHAIN;
typedef struct sockaddr // Size=16
{
    unsigned short sa_family; // Size=2 Offset=0
    char sa_data[14]; // Size=14 Offset=2
} *Psockaddr;
typedef class CLoopThread // Size=16
{
    int m_bRunThread; // Size=4 Offset=4
    void * m_hThread; // Size=4 Offset=8
    unsigned long m_dwThreadID; // Size=4 Offset=12
} *PCLoopThread;
typedef struct _WSANETWORKEVENTS // Size=44
{
    long lNetworkEvents; // Size=4 Offset=0
    int iErrorCode[10]; // Size=40 Offset=4
} WSANETWORKEVENTS, *PWSANETWORKEVENTS;
typedef struct _ITEM_ID_ // Size=8
{
    unsigned long id; // Size=4 Offset=0
    struct
    {
        unsigned long code: 14; // Size=4 Offset=4 BitOffset=0 BitCount=14
        unsigned long subcode: 18; // Size=4 Offset=4 BitOffset=14 BitCount=18
    };
} ITEM_ID_, *PITEM_ID_;
typedef union _ITEM_INFO_ // Size=4
{
    unsigned long info; // Size=4 Offset=0
    unsigned short money; // Size=2 Offset=0
    unsigned short quantity; // Size=2 Offset=0
    struct
    {
        unsigned long level: 4; // Size=4 Offset=0 BitOffset=0 BitCount=4
        unsigned long option: 1; // Size=4 Offset=0 BitOffset=4 BitCount=1
        unsigned long confirm: 1; // Size=4 Offset=0 BitOffset=5 BitCount=1
        unsigned long subtype: 4; // Size=4 Offset=0 BitOffset=6 BitCount=4
        unsigned long wearIdx: 4; // Size=4 Offset=0 BitOffset=10 BitCount=4
        unsigned long iceAttr: 6; // Size=4 Offset=0 BitOffset=14 BitCount=6
        unsigned long fireAttr: 6; // Size=4 Offset=0 BitOffset=20 BitCount=6
        unsigned long lightAttr: 6; // Size=4 Offset=0 BitOffset=26 BitCount=6
    };
} ITEM_INFO_, *PITEM_INFO_;
typedef union _ITEM_SERIALKEY_ // Size=4
{
    unsigned long serialKey; // Size=4 Offset=0
    struct
    {
        unsigned long year: 4; // Size=4 Offset=0 BitOffset=0 BitCount=4
        unsigned long month: 4; // Size=4 Offset=0 BitOffset=4 BitCount=4
        unsigned long day: 4; // Size=4 Offset=0 BitOffset=8 BitCount=4
        unsigned long origin: 4; // Size=4 Offset=0 BitOffset=12 BitCount=4
        unsigned long count: 16; // Size=4 Offset=0 BitOffset=16 BitCount=16
    };
} ITEM_SERIALKEY_, *PITEM_SERIALKEY_;
typedef struct _SKILL_ // Size=8
{
    unsigned long skill_low; // Size=4 Offset=0
    unsigned long skill_high; // Size=4 Offset=4
} SKILL_, *PSKILL_;
typedef struct _SOCIALINFO_ // Size=4
{
    unsigned long nation: 8; // Size=4 Offset=0 BitOffset=0 BitCount=8
    unsigned long rank: 8; // Size=4 Offset=0 BitOffset=8 BitCount=8
    unsigned long knight_index: 16; // Size=4 Offset=0 BitOffset=16 BitCount=16
} SOCIALINFO_, *PSOCIALINFO_;
typedef class MSG_S2G_HEADER // Size=10
{
    unsigned long dwSize; // Size=4 Offset=0
    unsigned long dwPCID; // Size=4 Offset=4
    unsigned char byCtrl; // Size=1 Offset=8
    unsigned char byCmd; // Size=1 Offset=9
} *PMSG_S2G_HEADER;
typedef class MSG_S2C_HEADER // Size=12
{
    unsigned long dwSize; // Size=4 Offset=0
    unsigned long dwPCID; // Size=4 Offset=4
    unsigned char byCtrl; // Size=1 Offset=8
    unsigned char byCmd; // Size=1 Offset=9
    unsigned short wProtocol; // Size=2 Offset=10
} *PMSG_S2C_HEADER;
typedef class MSG_S2C_ERROR // Size=78
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned short wErrCode; // Size=2 Offset=12
    char szErrStr[64]; // Size=64 Offset=14
} *PMSG_S2C_ERROR;
typedef class MSG_S2C_PC_DISAPPEAR // Size=16
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned long dwPCID; // Size=4 Offset=12
} *PMSG_S2C_PC_DISAPPEAR;
typedef class MSG_S2C_CHAR_LOGIN_OK // Size=31
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    char szPCName[13]; // Size=13 Offset=12
    unsigned long dwPCID; // Size=4 Offset=25
    unsigned short wMapIndex; // Size=2 Offset=29
} *PMSG_S2C_CHAR_LOGIN_OK;
typedef class MSG_S2C_ANS_MOVE // Size=17
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned char bAns; // Size=1 Offset=12
    unsigned long dwDestCell; // Size=4 Offset=13
} *PMSG_S2C_ANS_MOVE;
typedef class MSG_S2C_SEE_MOVE // Size=24
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned long dwMovePCID; // Size=4 Offset=12
    unsigned long dwStartCell; // Size=4 Offset=16
    unsigned long dwDestCell; // Size=4 Offset=20
} *PMSG_S2C_SEE_MOVE;
typedef class MSG_S2C_FIX_MOVE // Size=16
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned long dwFixCell; // Size=4 Offset=12
} *PMSG_S2C_FIX_MOVE;
typedef class MSG_S2C_SEE_STOP // Size=20
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned long dwStopPCID; // Size=4 Offset=12
    unsigned long dwFixCell; // Size=4 Offset=16
} *PMSG_S2C_SEE_STOP;
typedef class MSG_S2S_HEADER // Size=2
{
    unsigned short wProtocol; // Size=2 Offset=0
} *PMSG_S2S_HEADER;
typedef class MSG_S2M_SVR_LOGIN // Size=3
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned char byThisServerID; // Size=1 Offset=2
} *PMSG_S2M_SVR_LOGIN;
typedef class MSG_S2M_CHAR_LOGIN // Size=156
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    unsigned char byGateSvrID; // Size=1 Offset=6
    char szAccountName[21]; // Size=21 Offset=7
    char szPasswd[21]; // Size=21 Offset=28
    char szPCName[13]; // Size=13 Offset=49
    char szIP[16]; // Size=16 Offset=62
    unsigned long RemainTime; // Size=4 Offset=78
    char PayMode[4]; // Size=4 Offset=82
    long PayNo; // Size=4 Offset=86
    char Reserved1[33]; // Size=33 Offset=90
    char Reserved2[33]; // Size=33 Offset=123
} *PMSG_S2M_CHAR_LOGIN;
typedef class MSG_S2M_WORLD_LOGIN // Size=19
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    char szPCName[13]; // Size=13 Offset=2
    unsigned long dwPCID; // Size=4 Offset=15
} *PMSG_S2M_WORLD_LOGIN;
typedef class MSG_S2G_DISCONNECT // Size=10
{
    class MSG_S2G_HEADER MsgHeader; // Size=10 Offset=0
} *PMSG_S2G_DISCONNECT;
typedef class MSG_S2G_SWITCH_ZONE // Size=11
{
    class MSG_S2G_HEADER MsgHeader; // Size=10 Offset=0
    unsigned char byNewServerID; // Size=1 Offset=10
} *PMSG_S2G_SWITCH_ZONE;
typedef class MSG_S2G_BROADCAST // Size=10
{
    class MSG_S2G_HEADER MsgHeader; // Size=10 Offset=0
} *PMSG_S2G_BROADCAST;
typedef class MSG_S2C_ANS_DELETE_PLAYER // Size=25
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    char szCharacterName[13]; // Size=13 Offset=12
} *PMSG_S2C_ANS_DELETE_PLAYER;
typedef class MSG_S2M_ASK_CREATE_PLAYER // Size=43
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    unsigned char byGateSvrID; // Size=1 Offset=6
    unsigned char byClassIndex; // Size=1 Offset=7
    unsigned char byNation; // Size=1 Offset=8
    char szCharacterName[13]; // Size=13 Offset=9
    char szAccountName[21]; // Size=21 Offset=22
} *PMSG_S2M_ASK_CREATE_PLAYER;
typedef class MSG_S2M_ASK_DELETE_PLAYER // Size=20
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    unsigned char byGateSvrID; // Size=1 Offset=6
    char szCharacterName[13]; // Size=13 Offset=7
} *PMSG_S2M_ASK_DELETE_PLAYER;
typedef class MSG_A2C_TRANSFER_MARK // Size=38
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    char szPCName[13]; // Size=13 Offset=12
    unsigned long dwClanID; // Size=4 Offset=25
    unsigned long dwMarkID; // Size=4 Offset=29
    unsigned long dwRandomNumber; // Size=4 Offset=33
    unsigned char byResultCode; // Size=1 Offset=37
} *PMSG_A2C_TRANSFER_MARK;
typedef class MSG_A2C_ANS_MARK // Size=1269
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned char byResultCode; // Size=1 Offset=12
    unsigned long dwMarkID; // Size=4 Offset=13
    unsigned short wClanIndex; // Size=2 Offset=17
    unsigned char Mark[1250]; // Size=1250 Offset=19
} *PMSG_A2C_ANS_MARK;
typedef class MSG_A2M_CONFIRM_MARK // Size=24
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    char szPCName[13]; // Size=13 Offset=2
    unsigned long dwClanID; // Size=4 Offset=15
    unsigned long dwMarkID; // Size=4 Offset=19
    unsigned char byResultCode; // Size=1 Offset=23
} *PMSG_A2M_CONFIRM_MARK;
typedef struct _iobuf // Size=32
{
    char * _ptr; // Size=4 Offset=0
    int _cnt; // Size=4 Offset=4
    char * _base; // Size=4 Offset=8
    int _flag; // Size=4 Offset=12
    int _file; // Size=4 Offset=16
    int _charbuf; // Size=4 Offset=20
    int _bufsiz; // Size=4 Offset=24
    char * _tmpfname; // Size=4 Offset=28
} iobuf, *Piobuf;
typedef struct std::input_iterator_tag // Size=1
{
} *Pstd::input_iterator_tag;
typedef struct std::forward_iterator_tag // Size=1
{
} *Pstd::forward_iterator_tag;
typedef struct std::bidirectional_iterator_tag // Size=1
{
} *Pstd::bidirectional_iterator_tag;
typedef struct std::iterator<std::input_iterator_tag,_C,_D> // Size=0
{
} *Pstd::iterator<std::input_iterator_tag,_C,_D>;
typedef struct std::iterator<std::input_iterator_tag,_C,int> // Size=0
{
} *Pstd::iterator<std::input_iterator_tag,_C,int>;
typedef class exception // Size=12
{
    char * _m_what; // Size=4 Offset=4
    int _m_doFree; // Size=4 Offset=8
} *Pexception;
typedef class std::bad_exception // Size=12
{
} *Pstd::bad_exception;
typedef struct _TypeDescriptor // Size=8
{
    void * pVFTable; // Size=4 Offset=0
    void * spare; // Size=4 Offset=4
} TypeDescriptor, *PTypeDescriptor;
typedef class std::bad_alloc // Size=12
{
} *Pstd::bad_alloc;
typedef struct std::_Bidit<_D,_D> // Size=0
{
} *Pstd::_Bidit<_D,_D>;
typedef struct std::unary_function<std::pair<_A,_R>,_A> // Size=0
{
} *Pstd::unary_function<std::pair<_A,_R>,_A>;
typedef struct std::binary_function<std::pair<_A1,_A2>,std::pair<_A1,_A2>,bool> // Size=0
{
} *Pstd::binary_function<std::pair<_A1,_A2>,std::pair<_A1,_A2>,bool>;
typedef class std::_Tree<_K,std::pair<_K,_Ty>,std::map<_K,_Ty,_Kfn,_Pr>::_Kfn,_Kfn,_Pr> // Size=0
{
} *Pstd::_Tree<_K,std::pair<_K,_Ty>,std::map<_K,_Ty,_Kfn,_Pr>::_Kfn,_Kfn,_Pr>;
typedef class std::_Tree<_K,std::pair<_K,_Ty>,std::multimap<_K,_Ty,_Kfn,_Pr>::_Kfn,_Kfn,_Pr> // Size=0
{
} *Pstd::_Tree<_K,std::pair<_K,_Ty>,std::multimap<_K,_Ty,_Kfn,_Pr>::_Kfn,_Kfn,_Pr>;
typedef struct std::_Bidit<std::pair<unsigned long const ,ACCOUNT_INFO *>,int> // Size=1
{
} *Pstd::_Bidit<std::pair<unsigned long const ,ACCOUNT_INFO *>,int>;
typedef struct std::pair<unsigned long const ,ACCOUNT_INFO *> // Size=8
{
    unsigned long first; // Size=4 Offset=0
    class ACCOUNT_INFO * second; // Size=4 Offset=4
} *Pstd::pair<unsigned long const ,ACCOUNT_INFO *>;
typedef class CSimpleCrypt // Size=16
{
    int m_ConstKey1; // Size=4 Offset=4
    int m_ConstKey2; // Size=4 Offset=8
    int m_DynamicKey; // Size=4 Offset=12
} *PCSimpleCrypt;
typedef class std::logic_error // Size=28
{
    class std::basic_string<char,std::char_traits<char>,std::allocator<char> > _Str; // Size=16 Offset=12
} *Pstd::logic_error;
typedef class std::reverse_iterator<char const *,char,char const &,char const *,int> // Size=0
{
} *Pstd::reverse_iterator<char const *,char,char const &,char const *,int>;
typedef class std::allocator<char> // Size=1
{
} *Pstd::allocator<char>;
typedef struct std::char_traits<char> // Size=1
{
} *Pstd::char_traits<char>;
typedef class std::domain_error // Size=28
{
} *Pstd::domain_error;
typedef class std::invalid_argument // Size=28
{
} *Pstd::invalid_argument;
typedef class std::length_error // Size=28
{
} *Pstd::length_error;
typedef class std::out_of_range // Size=28
{
} *Pstd::out_of_range;
typedef class std::runtime_error // Size=28
{
    class std::basic_string<char,std::char_traits<char>,std::allocator<char> > _Str; // Size=16 Offset=12
} *Pstd::runtime_error;
typedef class std::overflow_error // Size=28
{
} *Pstd::overflow_error;
typedef class std::underflow_error // Size=28
{
} *Pstd::underflow_error;
typedef class std::range_error // Size=28
{
} *Pstd::range_error;
typedef struct std::iterator<std::bidirectional_iterator_tag,_C,_Ty> // Size=0
{
} *Pstd::iterator<std::bidirectional_iterator_tag,_C,_Ty>;
typedef struct tagSQL_YEAR_MONTH // Size=8
{
    unsigned long year; // Size=4 Offset=0
    unsigned long month; // Size=4 Offset=4
} *PtagSQL_YEAR_MONTH;
typedef struct tagSQL_DAY_SECOND // Size=20
{
    unsigned long day; // Size=4 Offset=0
    unsigned long hour; // Size=4 Offset=4
    unsigned long minute; // Size=4 Offset=8
    unsigned long second; // Size=4 Offset=12
    unsigned long fraction; // Size=4 Offset=16
} *PtagSQL_DAY_SECOND;
typedef class CODBC // Size=12
{
    void * m_hEnv; // Size=4 Offset=4
    void * m_hDbc; // Size=4 Offset=8
} *PCODBC;
typedef class CShareObject // Size=8
{
    long m_lockFlag; // Size=4 Offset=0
    long m_refCnt; // Size=4 Offset=4
} *PCShareObject;
typedef struct std::_Bidit<_DB_QUERY_ *,int> // Size=1
{
} *Pstd::_Bidit<_DB_QUERY_ *,int>;
typedef class CUDPSock // Size=1036
{
    unsigned int m_hSocket; // Size=4 Offset=4
    void * m_wsaEvent; // Size=4 Offset=8
    char m_ReadBuf[1024]; // Size=1024 Offset=12
} *PCUDPSock;
typedef class MarkData // Size=1268
{
    unsigned long dwClanID; // Size=4 Offset=0
    unsigned long dwMarkID; // Size=4 Offset=4
    unsigned char mark[1250]; // Size=1250 Offset=8
    unsigned long dwPreviousMarkID; // Size=4 Offset=1260
    unsigned long dwReserved; // Size=4 Offset=1264
} *PMarkData;
typedef class CAccntCharacDB // Size=208
{
    int m_bConnect; // Size=4 Offset=28
    unsigned char m_byWorldIndex; // Size=1 Offset=32
    char m_szDBServer[64]; // Size=64 Offset=33
    char m_szLogin[32]; // Size=32 Offset=97
    char m_szPasswd[32]; // Size=32 Offset=129
    int m_iRetry; // Size=4 Offset=164
    class std::list<_DB_QUERY_ *,std::allocator<_DB_QUERY_ *> > m_DBQueryQ; // Size=12 Offset=168
    class CSyncSection m_SyncDBQueryQ; // Size=28 Offset=180
} *PCAccntCharacDB;
typedef class std::allocator<_DB_QUERY_ *> // Size=1
{
} *Pstd::allocator<_DB_QUERY_ *>;
typedef class std::reverse_bidirectional_iterator<std::list<_DB_QUERY_ *,std::allocator<_DB_QUERY_ *> >::iterator,_DB_QUERY_ *,_DB_QUERY_ * &,_DB_QUERY_ * *,int> // Size=0
{
} *Pstd::reverse_bidirectional_iterator<std::list<_DB_QUERY_ *,std::allocator<_DB_QUERY_ *> >::iterator,_DB_QUERY_ *,_DB_QUERY_ * &,_DB_QUERY_ * *,int>;
typedef struct std::not_equal_to<_DB_QUERY_ *> // Size=1
{
} *Pstd::not_equal_to<_DB_QUERY_ *>;
typedef struct std::greater<_DB_QUERY_ *> // Size=1
{
} *Pstd::greater<_DB_QUERY_ *>;
typedef class std::basic_string // Size=0
{
} *Pstd::basic_string;
typedef struct std::char_traits<unsigned short> // Size=1
{
} *Pstd::char_traits<unsigned short>;
typedef class std::fpos<int> // Size=0
{
} *Pstd::fpos<int>;
typedef struct HWND__ // Size=4
{
    int unused; // Size=4 Offset=0
} *PHWND__;
typedef struct _ULARGE_INTEGER::__unnamed // Size=8
{
    unsigned long LowPart; // Size=4 Offset=0
    unsigned long HighPart; // Size=4 Offset=4
} ULARGE_INTEGER::__unnamed, *PULARGE_INTEGER::__unnamed;
typedef struct _PMD // Size=12
{
    int mdisp; // Size=4 Offset=0
    int pdisp; // Size=4 Offset=4
    int vdisp; // Size=4 Offset=8
} PMD, *PPMD;
typedef struct HDRVR__ // Size=4
{
    int unused; // Size=4 Offset=0
} *PHDRVR__;
typedef struct tagLOGFONTW // Size=92
{
    long lfHeight; // Size=4 Offset=0
    long lfWidth; // Size=4 Offset=4
    long lfEscapement; // Size=4 Offset=8
    long lfOrientation; // Size=4 Offset=12
    long lfWeight; // Size=4 Offset=16
    unsigned char lfItalic; // Size=1 Offset=20
    unsigned char lfUnderline; // Size=1 Offset=21
    unsigned char lfStrikeOut; // Size=1 Offset=22
    unsigned char lfCharSet; // Size=1 Offset=23
    unsigned char lfOutPrecision; // Size=1 Offset=24
    unsigned char lfClipPrecision; // Size=1 Offset=25
    unsigned char lfQuality; // Size=1 Offset=26
    unsigned char lfPitchAndFamily; // Size=1 Offset=27
    unsigned short lfFaceName[32]; // Size=64 Offset=28
} *PtagLOGFONTW;
typedef struct tagTEXTMETRICW // Size=60
{
    long tmHeight; // Size=4 Offset=0
    long tmAscent; // Size=4 Offset=4
    long tmDescent; // Size=4 Offset=8
    long tmInternalLeading; // Size=4 Offset=12
    long tmExternalLeading; // Size=4 Offset=16
    long tmAveCharWidth; // Size=4 Offset=20
    long tmMaxCharWidth; // Size=4 Offset=24
    long tmWeight; // Size=4 Offset=28
    long tmOverhang; // Size=4 Offset=32
    long tmDigitizedAspectX; // Size=4 Offset=36
    long tmDigitizedAspectY; // Size=4 Offset=40
    unsigned short tmFirstChar; // Size=2 Offset=44
    unsigned short tmLastChar; // Size=2 Offset=46
    unsigned short tmDefaultChar; // Size=2 Offset=48
    unsigned short tmBreakChar; // Size=2 Offset=50
    unsigned char tmItalic; // Size=1 Offset=52
    unsigned char tmUnderlined; // Size=1 Offset=53
    unsigned char tmStruckOut; // Size=1 Offset=54
    unsigned char tmPitchAndFamily; // Size=1 Offset=55
    unsigned char tmCharSet; // Size=1 Offset=56
} *PtagTEXTMETRICW;
typedef struct tagLOGFONTA // Size=60
{
    long lfHeight; // Size=4 Offset=0
    long lfWidth; // Size=4 Offset=4
    long lfEscapement; // Size=4 Offset=8
    long lfOrientation; // Size=4 Offset=12
    long lfWeight; // Size=4 Offset=16
    unsigned char lfItalic; // Size=1 Offset=20
    unsigned char lfUnderline; // Size=1 Offset=21
    unsigned char lfStrikeOut; // Size=1 Offset=22
    unsigned char lfCharSet; // Size=1 Offset=23
    unsigned char lfOutPrecision; // Size=1 Offset=24
    unsigned char lfClipPrecision; // Size=1 Offset=25
    unsigned char lfQuality; // Size=1 Offset=26
    unsigned char lfPitchAndFamily; // Size=1 Offset=27
    char lfFaceName[32]; // Size=32 Offset=28
} *PtagLOGFONTA;
typedef struct tagTEXTMETRICA // Size=56
{
    long tmHeight; // Size=4 Offset=0
    long tmAscent; // Size=4 Offset=4
    long tmDescent; // Size=4 Offset=8
    long tmInternalLeading; // Size=4 Offset=12
    long tmExternalLeading; // Size=4 Offset=16
    long tmAveCharWidth; // Size=4 Offset=20
    long tmMaxCharWidth; // Size=4 Offset=24
    long tmWeight; // Size=4 Offset=28
    long tmOverhang; // Size=4 Offset=32
    long tmDigitizedAspectX; // Size=4 Offset=36
    long tmDigitizedAspectY; // Size=4 Offset=40
    unsigned char tmFirstChar; // Size=1 Offset=44
    unsigned char tmLastChar; // Size=1 Offset=45
    unsigned char tmDefaultChar; // Size=1 Offset=46
    unsigned char tmBreakChar; // Size=1 Offset=47
    unsigned char tmItalic; // Size=1 Offset=48
    unsigned char tmUnderlined; // Size=1 Offset=49
    unsigned char tmStruckOut; // Size=1 Offset=50
    unsigned char tmPitchAndFamily; // Size=1 Offset=51
    unsigned char tmCharSet; // Size=1 Offset=52
} *PtagTEXTMETRICA;
typedef struct HINSTANCE__ // Size=4
{
    int unused; // Size=4 Offset=0
} *PHINSTANCE__;
typedef struct HDC__ // Size=4
{
    int unused; // Size=4 Offset=0
} *PHDC__;
typedef struct _OVERLAPPED // Size=20
{
    unsigned long Internal; // Size=4 Offset=0
    unsigned long InternalHigh; // Size=4 Offset=4
    unsigned long Offset; // Size=4 Offset=8
    unsigned long OffsetHigh; // Size=4 Offset=12
    void * hEvent; // Size=4 Offset=16
} OVERLAPPED, *POVERLAPPED;
typedef struct val_context // Size=12
{
    int valuelen; // Size=4 Offset=0
    void * value_context; // Size=4 Offset=4
    void * val_buff_ptr; // Size=4 Offset=8
} *Pval_context;
typedef struct IUnknown // Size=4
{
} *PIUnknown;
typedef struct IEnumSTATSTG // Size=4
{
} *PIEnumSTATSTG;
typedef struct tagHANDLETABLE // Size=4
{
    void * objectHandle[1]; // Size=4 Offset=0
} *PtagHANDLETABLE;
typedef struct tagENHMETARECORD // Size=12
{
    unsigned long iType; // Size=4 Offset=0
    unsigned long nSize; // Size=4 Offset=4
    unsigned long dParm[1]; // Size=4 Offset=8
} *PtagENHMETARECORD;
typedef struct std::binary_function<_DB_QUERY_ *,_DB_QUERY_ *,bool> // Size=1
{
} *Pstd::binary_function<_DB_QUERY_ *,_DB_QUERY_ *,bool>;
typedef class std::reverse_bidirectional_iterator<std::_Tree<unsigned long,std::pair<unsigned long const ,ACCOUNT_INFO *>,std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Kfn,std::less<unsigned long>,std::allocat55968ead // Size=0
{
} *Pstd::reverse_bidirectional_iterator<std::_Tree<unsigned long,std::pair<unsigned long const ,ACCOUNT_INFO *>,std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Kfn,std::less<unsigned long>,std::allocat55968ead;
typedef struct std::pair<std::_Tree<unsigned long,std::pair<unsigned long const ,ACCOUNT_INFO *>,std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Kfn,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::iter3231b474 // Size=8
{
    class std::_Tree<unsigned long,std::pair<unsigned long const ,ACCOUNT_INFO *>,std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Kfn,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::iterator first; // Size=4 Offset=0
    unsigned char second; // Size=1 Offset=4
} *Pstd::pair<std::_Tree<unsigned long,std::pair<unsigned long const ,ACCOUNT_INFO *>,std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Kfn,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::iter3231b474;
typedef struct std::less<unsigned long> // Size=1
{
} *Pstd::less<unsigned long>;
typedef class std::allocator<ACCOUNT_INFO *> // Size=1
{
} *Pstd::allocator<ACCOUNT_INFO *>;
typedef struct std::binary_function<unsigned long,unsigned long,bool> // Size=1
{
} *Pstd::binary_function<unsigned long,unsigned long,bool>;
typedef struct std::iterator<std::bidirectional_iterator_tag,std::pair<unsigned long const ,ACCOUNT_INFO *>,int> // Size=1
{
} *Pstd::iterator<std::bidirectional_iterator_tag,std::pair<unsigned long const ,ACCOUNT_INFO *>,int>;
typedef struct std::unary_function<_DB_QUERY_ *,bool> // Size=1
{
} *Pstd::unary_function<_DB_QUERY_ *,bool>;
typedef struct std::iterator<std::bidirectional_iterator_tag,_DB_QUERY_ *,int> // Size=1
{
} *Pstd::iterator<std::bidirectional_iterator_tag,_DB_QUERY_ *,int>;
typedef class std::allocator<MarkData> // Size=1
{
} *Pstd::allocator<MarkData>;
typedef struct _LARGE_INTEGER::__unnamed // Size=8
{
    unsigned long LowPart; // Size=4 Offset=0
    long HighPart; // Size=4 Offset=4
} LARGE_INTEGER::__unnamed, *PLARGE_INTEGER::__unnamed;
typedef struct _RPC_VERSION // Size=4
{
    unsigned short MajorVersion; // Size=2 Offset=0
    unsigned short MinorVersion; // Size=2 Offset=2
} RPC_VERSION, *PRPC_VERSION;
typedef struct ISequentialStream // Size=4
{
} *PISequentialStream;
typedef struct tagMETARECORD // Size=8
{
    unsigned long rdSize; // Size=4 Offset=0
    unsigned short rdFunction; // Size=2 Offset=4
    unsigned short rdParm[1]; // Size=2 Offset=6
} *PtagMETARECORD;
typedef struct DLGTEMPLATE // Size=18
{
    unsigned long style; // Size=4 Offset=0
    unsigned long dwExtendedStyle; // Size=4 Offset=4
    unsigned short cdit; // Size=2 Offset=8
    short x; // Size=2 Offset=10
    short y; // Size=2 Offset=12
    short cx; // Size=2 Offset=14
    short cy; // Size=2 Offset=16
} *PDLGTEMPLATE;
typedef struct HICON__ // Size=4
{
    int unused; // Size=4 Offset=0
} *PHICON__;
typedef struct tagPOINT // Size=8
{
    long x; // Size=4 Offset=0
    long y; // Size=4 Offset=4
} *PtagPOINT;
typedef struct _PSP // Size=0
{
} PSP, *PPSP;
typedef struct ___unnamed477 // Size=12
{
    void * pad[2]; // Size=8 Offset=0
    void * userContext; // Size=4 Offset=8
} __unnamed477, *P__unnamed477;
typedef struct IRpcChannelBuffer // Size=4
{
} *PIRpcChannelBuffer;
typedef struct ARRAY_INFO // Size=24
{
    long Dimension; // Size=4 Offset=0
    unsigned long * BufferConformanceMark; // Size=4 Offset=4
    unsigned long * BufferVarianceMark; // Size=4 Offset=8
    unsigned long * MaxCountArray; // Size=4 Offset=12
    unsigned long * OffsetArray; // Size=4 Offset=16
    unsigned long * ActualCountArray; // Size=4 Offset=20
} *PARRAY_INFO;
typedef struct _NDR_PIPE_DESC // Size=0
{
} NDR_PIPE_DESC, *PNDR_PIPE_DESC;
typedef struct _NDR_ASYNC_MESSAGE // Size=0
{
} NDR_ASYNC_MESSAGE, *PNDR_ASYNC_MESSAGE;
typedef struct _FLOATING_SAVE_AREA // Size=112
{
    unsigned long ControlWord; // Size=4 Offset=0
    unsigned long StatusWord; // Size=4 Offset=4
    unsigned long TagWord; // Size=4 Offset=8
    unsigned long ErrorOffset; // Size=4 Offset=12
    unsigned long ErrorSelector; // Size=4 Offset=16
    unsigned long DataOffset; // Size=4 Offset=20
    unsigned long DataSelector; // Size=4 Offset=24
    unsigned char RegisterArea[80]; // Size=80 Offset=28
    unsigned long Cr0NpxState; // Size=4 Offset=108
} FLOATING_SAVE_AREA, *PFLOATING_SAVE_AREA;
typedef struct __GENERIC_BINDING_INFO // Size=16
{
    void * pObj; // Size=4 Offset=0
    unsigned int Size; // Size=4 Offset=4
    void * ( * pfnBind)(void *); // Size=4 Offset=8
    void ( * pfnUnbind)(void *,unsigned char *); // Size=4 Offset=12
} _GENERIC_BINDING_INFO, *P_GENERIC_BINDING_INFO;
typedef struct _GENERIC_BINDING_ROUTINE_PAIR // Size=8
{
    void * ( * pfnBind)(void *); // Size=4 Offset=0
    void ( * pfnUnbind)(void *,unsigned char *); // Size=4 Offset=4
} GENERIC_BINDING_ROUTINE_PAIR, *PGENERIC_BINDING_ROUTINE_PAIR;
typedef struct _XMIT_ROUTINE_QUINTUPLE // Size=16
{
    void ( * pfnTranslateToXmit)(struct _MIDL_STUB_MESSAGE *); // Size=4 Offset=0
    void ( * pfnTranslateFromXmit)(struct _MIDL_STUB_MESSAGE *); // Size=4 Offset=4
    void ( * pfnFreeXmit)(struct _MIDL_STUB_MESSAGE *); // Size=4 Offset=8
    void ( * pfnFreeInst)(struct _MIDL_STUB_MESSAGE *); // Size=4 Offset=12
} XMIT_ROUTINE_QUINTUPLE, *PXMIT_ROUTINE_QUINTUPLE;
typedef struct _MALLOC_FREE_STRUCT // Size=8
{
    void * ( * pfnAllocate)(unsigned int); // Size=4 Offset=0
    void ( * pfnFree)(void *); // Size=4 Offset=4
} MALLOC_FREE_STRUCT, *PMALLOC_FREE_STRUCT;
typedef struct _COMM_FAULT_OFFSETS // Size=4
{
    short CommOffset; // Size=2 Offset=0
    short FaultOffset; // Size=2 Offset=2
} COMM_FAULT_OFFSETS, *PCOMM_FAULT_OFFSETS;
typedef struct _USER_MARSHAL_ROUTINE_QUADRUPLE // Size=16
{
    unsigned long ( * pfnBufferSize)(unsigned long *,unsigned long,void *); // Size=4 Offset=0
    unsigned char * ( * pfnMarshall)(unsigned long *,unsigned char *,void *); // Size=4 Offset=4
    unsigned char * ( * pfnUnmarshall)(unsigned long *,unsigned char *,void *); // Size=4 Offset=8
    void ( * pfnFree)(unsigned long *,void *); // Size=4 Offset=12
} USER_MARSHAL_ROUTINE_QUADRUPLE, *PUSER_MARSHAL_ROUTINE_QUADRUPLE;
typedef struct _FULL_PTR_XLAT_TABLES::__unnamed // Size=12
{
    void * * XlatTable; // Size=4 Offset=0
    unsigned char * StateTable; // Size=4 Offset=4
    unsigned long NumberOfEntries; // Size=4 Offset=8
} FULL_PTR_XLAT_TABLES::__unnamed, *PFULL_PTR_XLAT_TABLES::__unnamed;
typedef struct tagRPCOLEMESSAGE // Size=44
{
    void * reserved1; // Size=4 Offset=0
    unsigned long dataRepresentation; // Size=4 Offset=4
    void * Buffer; // Size=4 Offset=8
    unsigned long cbBuffer; // Size=4 Offset=12
    unsigned long iMethod; // Size=4 Offset=16
    void * reserved2[5]; // Size=20 Offset=20
    unsigned long rpcFlags; // Size=4 Offset=40
} *PtagRPCOLEMESSAGE;
typedef class std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> > // Size=16
{
    class std::_Tree<unsigned long,std::pair<unsigned long const ,ACCOUNT_INFO *>,std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Kfn,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> > _Tr; // Size=16 Offset=0
} *Pstd::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >;
typedef class std::_Lockit // Size=1
{
} *Pstd::_Lockit;
typedef struct std::unary_function<std::pair<unsigned long const ,ACCOUNT_INFO *>,unsigned long> // Size=1
{
} *Pstd::unary_function<std::pair<unsigned long const ,ACCOUNT_INFO *>,unsigned long>;
typedef class std::_Tree // Size=0
{
} *Pstd::_Tree;
typedef struct std::binary_function<std::pair<unsigned long const ,ACCOUNT_INFO *>,std::pair<unsigned long const ,ACCOUNT_INFO *>,bool> // Size=1
{
} *Pstd::binary_function<std::pair<unsigned long const ,ACCOUNT_INFO *>,std::pair<unsigned long const ,ACCOUNT_INFO *>,bool>;
typedef struct HBRUSH__ // Size=4
{
    int unused; // Size=4 Offset=0
} *PHBRUSH__;
typedef struct tagRECT // Size=16
{
    long left; // Size=4 Offset=0
    long top; // Size=4 Offset=4
    long right; // Size=4 Offset=8
    long bottom; // Size=4 Offset=12
} *PtagRECT;
typedef class CLoopSleepMgr // Size=20
{
    int m_iInterval; // Size=4 Offset=4
    unsigned long m_dwLongSleep; // Size=4 Offset=8
    unsigned long m_dwShortSleep; // Size=4 Offset=12
    int m_iCounter; // Size=4 Offset=16
} *PCLoopSleepMgr;
typedef struct tm // Size=36
{
    int tm_sec; // Size=4 Offset=0
    int tm_min; // Size=4 Offset=4
    int tm_hour; // Size=4 Offset=8
    int tm_mday; // Size=4 Offset=12
    int tm_mon; // Size=4 Offset=16
    int tm_year; // Size=4 Offset=20
    int tm_wday; // Size=4 Offset=24
    int tm_yday; // Size=4 Offset=28
    int tm_isdst; // Size=4 Offset=32
} *Ptm;
typedef class CMsgCrypt // Size=20
{
    int m_iMsgHeaderSize; // Size=4 Offset=16
} *PCMsgCrypt;
typedef class CGateServer // Size=8388728
{
    int m_bRunServer; // Size=4 Offset=8388720
    unsigned char m_bySvrID; // Size=1 Offset=8388724
} *PCGateServer;
typedef class MSG_DFLT_HEADER // Size=10
{
    unsigned long dwSize; // Size=4 Offset=0
    unsigned long dwPCID; // Size=4 Offset=4
    unsigned char byCtrl; // Size=1 Offset=8
    unsigned char byCmd; // Size=1 Offset=9
} *PMSG_DFLT_HEADER;
typedef class MSG_G2S_NEW_CLIENT // Size=146
{
    class MSG_S2G_HEADER MsgHeader; // Size=10 Offset=0
    char szAccountName[21]; // Size=21 Offset=10
    char szPasswd[21]; // Size=21 Offset=31
    char szIP[16]; // Size=16 Offset=52
    unsigned long RemainTime; // Size=4 Offset=68
    char PayMode[4]; // Size=4 Offset=72
    long PayNo; // Size=4 Offset=76
    char Reserved1[33]; // Size=33 Offset=80
    char Reserved2[33]; // Size=33 Offset=113
} *PMSG_G2S_NEW_CLIENT;
typedef class MSG_G2S_DISCONNECT // Size=11
{
    class MSG_S2G_HEADER MsgHeader; // Size=10 Offset=0
    unsigned char byReason; // Size=1 Offset=10
} *PMSG_G2S_DISCONNECT;
typedef class MSG_C2S_CHAR_LOGIN // Size=29
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    char szPCName[13]; // Size=13 Offset=12
    int CurVersion; // Size=4 Offset=25
} *PMSG_C2S_CHAR_LOGIN;
typedef class MSG_C2S_ASK_CREATE_PLAYER // Size=27
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned char byClassIndex; // Size=1 Offset=12
    unsigned char byNation; // Size=1 Offset=13
    char szCharacterName[13]; // Size=13 Offset=14
} *PMSG_C2S_ASK_CREATE_PLAYER;
typedef class MSG_C2S_ASK_DELETE_PLAYER // Size=25
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    char szCharacterName[13]; // Size=13 Offset=12
} *PMSG_C2S_ASK_DELETE_PLAYER;
typedef class MSG_C2A_TRANSFER_MARK // Size=1287
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    char szPCName[13]; // Size=13 Offset=12
    unsigned long dwClanID; // Size=4 Offset=25
    unsigned long dwMarkID; // Size=4 Offset=29
    unsigned long dwRandomNumber; // Size=4 Offset=33
    unsigned char Mark[1250]; // Size=1250 Offset=37
} *PMSG_C2A_TRANSFER_MARK;
typedef class MSG_C2A_ASK_MARK // Size=16
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned long dwMarkID; // Size=4 Offset=12
} *PMSG_C2A_ASK_MARK;
typedef struct WSAData // Size=400
{
    unsigned short wVersion; // Size=2 Offset=0
    unsigned short wHighVersion; // Size=2 Offset=2
    char szDescription[257]; // Size=257 Offset=4
    char szSystemStatus[129]; // Size=129 Offset=261
    unsigned short iMaxSockets; // Size=2 Offset=390
    unsigned short iMaxUdpDg; // Size=2 Offset=392
    char * lpVendorInfo; // Size=4 Offset=396
} *PWSAData;
typedef class CSvrManage // Size=36
{
    class CGateServer * m_GateServer; // Size=4 Offset=0
    int m_iGateServerNum; // Size=4 Offset=4
    int m_bSocketActive; // Size=4 Offset=8
    class CStandbyServer * m_pStandbyServer[5]; // Size=20 Offset=12
    int m_iStandbyServerNum; // Size=4 Offset=32
} *PCSvrManage;
typedef class CStandbyServer // Size=8388728
{
    int m_iIndex; // Size=4 Offset=8388720
    int m_bLogin; // Size=4 Offset=8388724
} *PCStandbyServer;
typedef struct _KDHELP // Size=28
{
    unsigned long Thread; // Size=4 Offset=0
    unsigned long ThCallbackStack; // Size=4 Offset=4
    unsigned long NextCallback; // Size=4 Offset=8
    unsigned long FramePointer; // Size=4 Offset=12
    unsigned long KiCallUserMode; // Size=4 Offset=16
    unsigned long KeUserCallbackDispatcher; // Size=4 Offset=20
    unsigned long SystemRangeStart; // Size=4 Offset=24
} KDHELP, *PKDHELP;
typedef struct _IMAGEHLP_SYMBOL // Size=24
{
    unsigned long SizeOfStruct; // Size=4 Offset=0
    unsigned long Address; // Size=4 Offset=4
    unsigned long Size; // Size=4 Offset=8
    unsigned long Flags; // Size=4 Offset=12
    unsigned long MaxNameLength; // Size=4 Offset=16
    char Name[1]; // Size=1 Offset=20
} IMAGEHLP_SYMBOL, *PIMAGEHLP_SYMBOL;
typedef struct _FPO_DATA // Size=16
{
    unsigned long ulOffStart; // Size=4 Offset=0
    unsigned long cbProcSize; // Size=4 Offset=4
    unsigned long cdwLocals; // Size=4 Offset=8
    unsigned short cdwParams; // Size=2 Offset=12
    struct
    {
        unsigned short cbProlog: 8; // Size=2 Offset=14 BitOffset=0 BitCount=8
        unsigned short cbRegs: 3; // Size=2 Offset=14 BitOffset=8 BitCount=3
        unsigned short fHasSEH: 1; // Size=2 Offset=14 BitOffset=11 BitCount=1
        unsigned short fUseBP: 1; // Size=2 Offset=14 BitOffset=12 BitCount=1
        unsigned short reserved: 1; // Size=2 Offset=14 BitOffset=13 BitCount=1
        unsigned short cbFrame: 2; // Size=2 Offset=14 BitOffset=14 BitCount=2
    };
} FPO_DATA, *PFPO_DATA;
typedef class _InternalExceptionHandlerClass // Size=1
{
} InternalExceptionHandlerClass, *PInternalExceptionHandlerClass;
typedef class CMainServer // Size=8388724
{
    int m_bRunServer; // Size=4 Offset=8388720
} *PCMainServer;
typedef class CTickManage // Size=32
{
    long m_lNowTick; // Size=4 Offset=0
    long m_lSecondNewDate; // Size=4 Offset=4
    long m_lSecondOClock; // Size=4 Offset=8
    long m_lSecond120; // Size=4 Offset=12
    long m_lSecond60; // Size=4 Offset=16
    long m_lSecond30; // Size=4 Offset=20
    long m_lSecond10; // Size=4 Offset=24
    long m_lSecond2; // Size=4 Offset=28
} *PCTickManage;
typedef class CMarkFDB // Size=20
{
    unsigned long dwLatestIssuedMarkID; // Size=4 Offset=0
    class std::map<unsigned long,MarkData,std::less<unsigned long>,std::allocator<MarkData> > ID2Data; // Size=16 Offset=4
} *PCMarkFDB;
typedef struct _SYSTEMTIME // Size=16
{
    unsigned short wYear; // Size=2 Offset=0
    unsigned short wMonth; // Size=2 Offset=2
    unsigned short wDayOfWeek; // Size=2 Offset=4
    unsigned short wDay; // Size=2 Offset=6
    unsigned short wHour; // Size=2 Offset=8
    unsigned short wMinute; // Size=2 Offset=10
    unsigned short wSecond; // Size=2 Offset=12
    unsigned short wMilliseconds; // Size=2 Offset=14
} SYSTEMTIME, *PSYSTEMTIME;
typedef class MSG_M2S_ERROR // Size=73
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    unsigned char byGateSvrID; // Size=1 Offset=6
    unsigned short wErrCode; // Size=2 Offset=7
    char szErrStr[64]; // Size=64 Offset=9
} *PMSG_M2S_ERROR;
typedef class MSG_M2S_CHAR_LOGIN // Size=10
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    unsigned char byGateSvrID; // Size=1 Offset=6
    unsigned char byNewZoneSvrID; // Size=1 Offset=7
    unsigned short wMapIndex; // Size=2 Offset=8
} *PMSG_M2S_CHAR_LOGIN;
typedef class MSG_M2S_ANS_CREATE_PLAYER // Size=20
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    unsigned char byGateSvrID; // Size=1 Offset=6
    char CharacterName[13]; // Size=13 Offset=7
} *PMSG_M2S_ANS_CREATE_PLAYER;
typedef class MSG_M2S_ANS_DELETE_PLAYER // Size=20
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    unsigned char byGateSvrID; // Size=1 Offset=6
    char CharacterName[13]; // Size=13 Offset=7
} *PMSG_M2S_ANS_DELETE_PLAYER;
typedef class MSG_M2A_REGISTER_MARK // Size=28
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    char szPCName[13]; // Size=13 Offset=2
    unsigned long dwPCID; // Size=4 Offset=15
    unsigned char byGateSvrID; // Size=1 Offset=19
    unsigned long dwClanID; // Size=4 Offset=20
    unsigned long dwMarkID; // Size=4 Offset=24
} *PMSG_M2A_REGISTER_MARK;
typedef class MSG_G2S_SVR_LOGIN // Size=11
{
    class MSG_S2G_HEADER MsgHeader; // Size=10 Offset=0
    unsigned char byThisServerID; // Size=1 Offset=10
} *PMSG_G2S_SVR_LOGIN;
typedef class MSG_HEADER // Size=2
{
    unsigned short wProtocol; // Size=2 Offset=0
} *PMSG_HEADER;
typedef class MSG_V2S_CMM_KILL // Size=2
{
    class MSG_HEADER MsgHeader; // Size=2 Offset=0
} *PMSG_V2S_CMM_KILL;
typedef class MSG_S2V_CMM_KILL // Size=2
{
    class MSG_HEADER MsgHeader; // Size=2 Offset=0
} *PMSG_S2V_CMM_KILL;
typedef class MSG_V2S_MAIN_SHOUT // Size=66
{
    class MSG_HEADER MsgHeader; // Size=2 Offset=0
    char szMsg[64]; // Size=64 Offset=2
} *PMSG_V2S_MAIN_SHOUT;
typedef class MSG_V2S_MAIN_WHISPER // Size=82
{
    class MSG_HEADER MsgHeader; // Size=2 Offset=0
    char szID[16]; // Size=16 Offset=2
    char szMsg[64]; // Size=64 Offset=18
} *PMSG_V2S_MAIN_WHISPER;
typedef class MSG_S2V_CMM_ALIVE // Size=2
{
    class MSG_HEADER MsgHeader; // Size=2 Offset=0
} *PMSG_S2V_CMM_ALIVE;
typedef class MSG_S2V_MAIN_SHOUT // Size=66
{
    class MSG_HEADER MsgHeader; // Size=2 Offset=0
    char szMsg[64]; // Size=64 Offset=2
} *PMSG_S2V_MAIN_SHOUT;
typedef struct _MAP_INFO_ // Size=4
{
    unsigned short wMapNum; // Size=2 Offset=0
    unsigned short wCurUser; // Size=2 Offset=2
} MAP_INFO_, *PMAP_INFO_;
typedef union _LARGE_INTEGER // Size=8
{
    struct
    {
        unsigned long LowPart; // Size=4 Offset=0
        long HighPart; // Size=4 Offset=4
    };
    struct _LARGE_INTEGER::___unnamed43 u; // Size=8 Offset=0
    __int64 QuadPart; // Size=8 Offset=0
} LARGE_INTEGER, *PLARGE_INTEGER;
typedef union _ULARGE_INTEGER // Size=8
{
    struct
    {
        unsigned long LowPart; // Size=4 Offset=0
        unsigned long HighPart; // Size=4 Offset=4
    };
    struct _ULARGE_INTEGER::___unnamed46 u; // Size=8 Offset=0
    unsigned __int64 QuadPart; // Size=8 Offset=0
} ULARGE_INTEGER, *PULARGE_INTEGER;
typedef struct tagCAH // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    union _LARGE_INTEGER * pElems; // Size=4 Offset=4
} *PtagCAH;
typedef struct tagCAUH // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    union _ULARGE_INTEGER * pElems; // Size=4 Offset=4
} *PtagCAUH;
typedef struct tagCACY // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    union tagCY * pElems; // Size=4 Offset=4
} *PtagCACY;
typedef struct tagCAFILETIME // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    struct _FILETIME * pElems; // Size=4 Offset=4
} *PtagCAFILETIME;
typedef struct tagCACLSID // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    struct _GUID * pElems; // Size=4 Offset=4
} *PtagCACLSID;
typedef struct tagCACLIPDATA // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    struct tagCLIPDATA * pElems; // Size=4 Offset=4
} *PtagCACLIPDATA;
typedef struct tagCABSTRBLOB // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    struct tagBSTRBLOB * pElems; // Size=4 Offset=4
} *PtagCABSTRBLOB;
typedef struct tagCAPROPVARIANT // Size=8
{
    unsigned long cElems; // Size=4 Offset=0
    struct tagPROPVARIANT * pElems; // Size=4 Offset=4
} *PtagCAPROPVARIANT;
typedef struct in_addr // Size=4
{
    union in_addr::___unnamed94 S_un; // Size=4 Offset=0
} *Pin_addr;
typedef struct _RSVP_FILTERSPEC_V4 // Size=8
{
    union _IN_ADDR_IPV4 Address; // Size=4 Offset=0
    unsigned short Unused; // Size=2 Offset=4
    unsigned short Port; // Size=2 Offset=6
} RSVP_FILTERSPEC_V4, *PRSVP_FILTERSPEC_V4;
typedef struct _RSVP_FILTERSPEC_V6 // Size=20
{
    struct _IN_ADDR_IPV6 Address; // Size=16 Offset=0
    unsigned short UnUsed; // Size=2 Offset=16
    unsigned short Port; // Size=2 Offset=18
} RSVP_FILTERSPEC_V6, *PRSVP_FILTERSPEC_V6;
typedef struct _RSVP_FILTERSPEC_V6_FLOW // Size=20
{
    struct _IN_ADDR_IPV6 Address; // Size=16 Offset=0
    unsigned char UnUsed; // Size=1 Offset=16
    unsigned char FlowLabel[3]; // Size=3 Offset=17
} RSVP_FILTERSPEC_V6_FLOW, *PRSVP_FILTERSPEC_V6_FLOW;
typedef struct _RSVP_FILTERSPEC_V4_GPI // Size=8
{
    union _IN_ADDR_IPV4 Address; // Size=4 Offset=0
    unsigned long GeneralPortId; // Size=4 Offset=4
} RSVP_FILTERSPEC_V4_GPI, *PRSVP_FILTERSPEC_V4_GPI;
typedef struct _RSVP_FILTERSPEC_V6_GPI // Size=20
{
    struct _IN_ADDR_IPV6 Address; // Size=16 Offset=0
    unsigned long GeneralPortId; // Size=4 Offset=16
} RSVP_FILTERSPEC_V6_GPI, *PRSVP_FILTERSPEC_V6_GPI;
typedef struct _SOCKET_ADDRESS // Size=8
{
    struct sockaddr * lpSockaddr; // Size=4 Offset=0
    int iSockaddrLength; // Size=4 Offset=4
} SOCKET_ADDRESS, *PSOCKET_ADDRESS;
typedef struct _RTL_CRITICAL_SECTION // Size=24
{
    struct _RTL_CRITICAL_SECTION_DEBUG * DebugInfo; // Size=4 Offset=0
    long LockCount; // Size=4 Offset=4
    long RecursionCount; // Size=4 Offset=8
    void * OwningThread; // Size=4 Offset=12
    void * LockSemaphore; // Size=4 Offset=16
    unsigned long SpinCount; // Size=4 Offset=20
} RTL_CRITICAL_SECTION, *PRTL_CRITICAL_SECTION;
typedef class std::list<_DB_QUERY_ *,std::allocator<_DB_QUERY_ *> > // Size=12
{
    class std::allocator<_DB_QUERY_ *> allocator; // Size=1 Offset=0
    struct std::list<_DB_QUERY_ *,std::allocator<_DB_QUERY_ *> >::_Node * _Head; // Size=4 Offset=4
    unsigned int _Size; // Size=4 Offset=8
} *Pstd::list<_DB_QUERY_ *,std::allocator<_DB_QUERY_ *> >;
typedef struct _DB_QUERY_ // Size=40
{
    enum _QUERY_TYPE_ QueryType; // Size=4 Offset=0
    char szAccountName[21]; // Size=21 Offset=4
    char szCharacterName[13]; // Size=13 Offset=25
    unsigned char byCharacType; // Size=1 Offset=38
    unsigned char byNationality; // Size=1 Offset=39
} DB_QUERY_, *PDB_QUERY_;
typedef struct _s__CatchableTypeArray // Size=4
{
    int nCatchableTypes; // Size=4 Offset=0
} s__CatchableTypeArray, *Ps__CatchableTypeArray;
typedef struct _s__ThrowInfo // Size=16
{
    unsigned int attributes; // Size=4 Offset=0
    void ( * pmfnUnwind)(); // Size=4 Offset=4
    int ( * pForwardCompat)(<NoType>); // Size=4 Offset=8
    struct _s__CatchableTypeArray * pCatchableTypeArray; // Size=4 Offset=12
} s__ThrowInfo, *Ps__ThrowInfo;
typedef struct _LIST_ENTRY // Size=8
{
    struct _LIST_ENTRY * Flink; // Size=4 Offset=0
    struct _LIST_ENTRY * Blink; // Size=4 Offset=4
} LIST_ENTRY, *PLIST_ENTRY;
typedef struct tagHELPINFO // Size=28
{
    unsigned int cbSize; // Size=4 Offset=0
    int iContextType; // Size=4 Offset=4
    int iCtrlId; // Size=4 Offset=8
    void * hItemHandle; // Size=4 Offset=12
    unsigned long dwContextId; // Size=4 Offset=16
    struct tagPOINT MousePos; // Size=8 Offset=20
} *PtagHELPINFO;
typedef struct _RPC_ASYNC_STATE::__unnamed::__unnamed // Size=8
{
    void ( * NotificationRoutine)(struct _RPC_ASYNC_STATE *,void *,enum _RPC_ASYNC_EVENT); // Size=4 Offset=0
    void * hThread; // Size=4 Offset=4
} RPC_ASYNC_STATE::__unnamed::__unnamed, *PRPC_ASYNC_STATE::__unnamed::__unnamed;
typedef struct _RPC_MESSAGE // Size=44
{
    void * Handle; // Size=4 Offset=0
    unsigned long DataRepresentation; // Size=4 Offset=4
    void * Buffer; // Size=4 Offset=8
    unsigned int BufferLength; // Size=4 Offset=12
    unsigned int ProcNum; // Size=4 Offset=16
    struct _RPC_SYNTAX_IDENTIFIER * TransferSyntax; // Size=4 Offset=20
    void * RpcInterfaceInformation; // Size=4 Offset=24
    void * ReservedForRuntime; // Size=4 Offset=28
    void * ManagerEpv; // Size=4 Offset=32
    void * ImportContext; // Size=4 Offset=36
    unsigned long RpcFlags; // Size=4 Offset=40
} RPC_MESSAGE, *PRPC_MESSAGE;
typedef struct _EXCEPTION_RECORD // Size=80
{
    unsigned long ExceptionCode; // Size=4 Offset=0
    unsigned long ExceptionFlags; // Size=4 Offset=4
    struct _EXCEPTION_RECORD * ExceptionRecord; // Size=4 Offset=8
    void * ExceptionAddress; // Size=4 Offset=12
    unsigned long NumberParameters; // Size=4 Offset=16
    unsigned long ExceptionInformation[15]; // Size=60 Offset=20
} EXCEPTION_RECORD, *PEXCEPTION_RECORD;
typedef struct _CONTEXT // Size=716
{
    unsigned long ContextFlags; // Size=4 Offset=0
    unsigned long Dr0; // Size=4 Offset=4
    unsigned long Dr1; // Size=4 Offset=8
    unsigned long Dr2; // Size=4 Offset=12
    unsigned long Dr3; // Size=4 Offset=16
    unsigned long Dr6; // Size=4 Offset=20
    unsigned long Dr7; // Size=4 Offset=24
    struct _FLOATING_SAVE_AREA FloatSave; // Size=112 Offset=28
    unsigned long SegGs; // Size=4 Offset=140
    unsigned long SegFs; // Size=4 Offset=144
    unsigned long SegEs; // Size=4 Offset=148
    unsigned long SegDs; // Size=4 Offset=152
    unsigned long Edi; // Size=4 Offset=156
    unsigned long Esi; // Size=4 Offset=160
    unsigned long Ebx; // Size=4 Offset=164
    unsigned long Edx; // Size=4 Offset=168
    unsigned long Ecx; // Size=4 Offset=172
    unsigned long Eax; // Size=4 Offset=176
    unsigned long Ebp; // Size=4 Offset=180
    unsigned long Eip; // Size=4 Offset=184
    unsigned long SegCs; // Size=4 Offset=188
    unsigned long EFlags; // Size=4 Offset=192
    unsigned long Esp; // Size=4 Offset=196
    unsigned long SegSs; // Size=4 Offset=200
    unsigned char ExtendedRegisters[512]; // Size=512 Offset=204
} CONTEXT, *PCONTEXT;
typedef union _MIDL_STUB_DESC::__unnamed // Size=4
{
    void * * pAutoHandle; // Size=4 Offset=0
    void * * pPrimitiveHandle; // Size=4 Offset=0
    struct __GENERIC_BINDING_INFO * pGenericBindingInfo; // Size=4 Offset=0
} MIDL_STUB_DESC::__unnamed, *PMIDL_STUB_DESC::__unnamed;
typedef struct _FULL_PTR_TO_REFID_ELEMENT // Size=16
{
    struct _FULL_PTR_TO_REFID_ELEMENT * Next; // Size=4 Offset=0
    void * Pointer; // Size=4 Offset=4
    unsigned long RefId; // Size=4 Offset=8
    unsigned char State; // Size=1 Offset=12
} FULL_PTR_TO_REFID_ELEMENT, *PFULL_PTR_TO_REFID_ELEMENT;
typedef class CAccountManage // Size=24
{
    class std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> > m_AccMap; // Size=16 Offset=0
    struct std::pair<std::_Tree<unsigned long,std::pair<unsigned long const ,ACCOUNT_INFO *>,std::map<unsigned long,ACCOUNT_INFO *,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::_Kfn,std::less<unsigned long>,std::allocator<ACCOUNT_INFO *> >::iter3231b474 m_pair; // Size=8 Offset=16
} *PCAccountManage;
typedef class CListenServer // Size=72
{
    unsigned int m_sSocket; // Size=4 Offset=16
    int m_bConnect; // Size=4 Offset=20
    void * m_wsaEvent; // Size=4 Offset=24
    struct _WSANETWORKEVENTS m_netEvent; // Size=44 Offset=28
} *PCListenServer;
typedef struct _tagADDRESS // Size=12
{
    unsigned long Offset; // Size=4 Offset=0
    unsigned short Segment; // Size=2 Offset=4
    enum ADDRESS_MODE Mode; // Size=4 Offset=8
} tagADDRESS, *PtagADDRESS;
typedef struct _IMAGEHLP_MODULE // Size=572
{
    unsigned long SizeOfStruct; // Size=4 Offset=0
    unsigned long BaseOfImage; // Size=4 Offset=4
    unsigned long ImageSize; // Size=4 Offset=8
    unsigned long TimeDateStamp; // Size=4 Offset=12
    unsigned long CheckSum; // Size=4 Offset=16
    unsigned long NumSyms; // Size=4 Offset=20
    enum SYM_TYPE SymType; // Size=4 Offset=24
    char ModuleName[32]; // Size=32 Offset=28
    char ImageName[256]; // Size=256 Offset=60
    char LoadedImageName[256]; // Size=256 Offset=316
} IMAGEHLP_MODULE, *PIMAGEHLP_MODULE;
typedef struct _ZONE_SERVER_INFO_ // Size=40
{
    struct _MAP_INFO_ arrMap[10]; // Size=40 Offset=0
} ZONE_SERVER_INFO_, *PZONE_SERVER_INFO_;
typedef union in_addr::__unnamed // Size=4
{
    struct in_addr::___unnamed95::___unnamed95 S_un_b; // Size=4 Offset=0
    struct in_addr::___unnamed96::___unnamed96 S_un_w; // Size=4 Offset=0
    unsigned long S_addr; // Size=4 Offset=0
} *Pin_addr::__unnamed;
typedef struct _ITEM_ // Size=16
{
    struct _ITEM_ID_ ItemID; // Size=8 Offset=0
    union _ITEM_INFO_ ItemInfo; // Size=4 Offset=8
    unsigned long ItemKey; // Size=4 Offset=12
} ITEM_, *PITEM_;
typedef struct _ACCOUNT_ITEM_ // Size=16
{
    struct _ITEM_ID_ ItemID; // Size=8 Offset=0
    union _ITEM_INFO_ ItemInfo; // Size=4 Offset=8
    unsigned char byWearIndex; // Size=1 Offset=12
} ACCOUNT_ITEM_, *PACCOUNT_ITEM_;
typedef class CSyncSection // Size=28
{
    struct _RTL_CRITICAL_SECTION m_cs; // Size=24 Offset=0
    unsigned char m_bLocked; // Size=1 Offset=24
} *PCSyncSection;
typedef struct sockaddr_in // Size=16
{
    short sin_family; // Size=2 Offset=0
    unsigned short sin_port; // Size=2 Offset=2
    struct in_addr sin_addr; // Size=4 Offset=4
    char sin_zero[8]; // Size=8 Offset=8
} *Psockaddr_in;
typedef class std::binder2nd<std::not_equal_to<_DB_QUERY_ *> > // Size=8
{
    struct std::not_equal_to<_DB_QUERY_ *> op; // Size=1 Offset=0
    struct _DB_QUERY_ * value; // Size=4 Offset=4
} *Pstd::binder2nd<std::not_equal_to<_DB_QUERY_ *> >;
typedef struct _s__CatchableType // Size=28
{
    unsigned int properties; // Size=4 Offset=0
    struct _TypeDescriptor * pType; // Size=4 Offset=4
    struct _PMD thisDisplacement; // Size=12 Offset=8
    int sizeOrOffset; // Size=4 Offset=20
    void ( * copyFunction)(); // Size=4 Offset=24
} s__CatchableType, *Ps__CatchableType;
typedef struct _QualityOfService // Size=72
{
    struct _flowspec SendingFlowspec; // Size=32 Offset=0
    struct _flowspec ReceivingFlowspec; // Size=32 Offset=32
    struct _WSABUF ProviderSpecific; // Size=8 Offset=64
} QualityOfService, *PQualityOfService;
typedef struct _EXCEPTION_POINTERS // Size=8
{
    struct _EXCEPTION_RECORD * ExceptionRecord; // Size=4 Offset=0
    struct _CONTEXT * ContextRecord; // Size=4 Offset=4
} EXCEPTION_POINTERS, *PEXCEPTION_POINTERS;
typedef struct _RPC_SYNTAX_IDENTIFIER // Size=20
{
    struct _GUID SyntaxGUID; // Size=16 Offset=0
    struct _RPC_VERSION SyntaxVersion; // Size=4 Offset=16
} RPC_SYNTAX_IDENTIFIER, *PRPC_SYNTAX_IDENTIFIER;
typedef struct tagMSG // Size=28
{
    struct HWND__ * hwnd; // Size=4 Offset=0
    unsigned int message; // Size=4 Offset=4
    unsigned int wParam; // Size=4 Offset=8
    long lParam; // Size=4 Offset=12
    unsigned long time; // Size=4 Offset=16
    struct tagPOINT pt; // Size=8 Offset=20
} *PtagMSG;
typedef struct tagPAINTSTRUCT // Size=64
{
    struct HDC__ * hdc; // Size=4 Offset=0
    int fErase; // Size=4 Offset=4
    struct tagRECT rcPaint; // Size=16 Offset=8
    int fRestore; // Size=4 Offset=24
    int fIncUpdate; // Size=4 Offset=28
    unsigned char rgbReserved[32]; // Size=32 Offset=32
} *PtagPAINTSTRUCT;
typedef class MSG_S2V_ZONE_INFO // Size=42
{
    class MSG_HEADER MsgHeader; // Size=2 Offset=0
    struct _ZONE_SERVER_INFO_ Info; // Size=40 Offset=2
} *PMSG_S2V_ZONE_INFO;
typedef struct _CONTROL_SERVICE // Size=44
{
    unsigned long Length; // Size=4 Offset=0
    unsigned long Service; // Size=4 Offset=4
    struct _AD_GENERAL_PARAMS Overrides; // Size=20 Offset=8
    union
    {
        struct _AD_GUARANTEED Guaranteed; // Size=16 Offset=28
        struct _PARAM_BUFFER ParamBuffer[1]; // Size=12 Offset=28
    };
} CONTROL_SERVICE, *PCONTROL_SERVICE;
typedef struct _CHARACTER_INFO_ // Size=180
{
    char szPCName[13]; // Size=13 Offset=0
    unsigned char byType; // Size=1 Offset=13
    unsigned char byNationality; // Size=1 Offset=14
    unsigned short wLevel; // Size=2 Offset=16
    struct _ACCOUNT_ITEM_ WearList[10]; // Size=160 Offset=20
} CHARACTER_INFO_, *PCHARACTER_INFO_;
typedef class CBaseServer // Size=8388720
{
    int m_bConnect; // Size=4 Offset=16
    unsigned int m_sSocket; // Size=4 Offset=20
    void * m_wsaEvent; // Size=4 Offset=24
    struct _WSANETWORKEVENTS m_netEvent; // Size=44 Offset=28
########################################
    int m_nRecvEndPos; // Size=4 Offset=4194380
########################################
    int m_nSendEndPos; // Size=4 Offset=8388692
    struct _RTL_CRITICAL_SECTION m_csSend; // Size=24 Offset=8388696
} *PCBaseServer;
typedef class MSG_S2C_ANS_CREATE_PLAYER // Size=186
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned char byClassIndex; // Size=1 Offset=12
    char szCharacterName[13]; // Size=13 Offset=13
    struct _ACCOUNT_ITEM_ WearList[10]; // Size=160 Offset=26
} *PMSG_S2C_ANS_CREATE_PLAYER;
typedef struct _RTL_CRITICAL_SECTION_DEBUG // Size=32
{
    unsigned short Type; // Size=2 Offset=0
    unsigned short CreatorBackTraceIndex; // Size=2 Offset=2
    struct _RTL_CRITICAL_SECTION * CriticalSection; // Size=4 Offset=4
    struct _LIST_ENTRY ProcessLocksList; // Size=8 Offset=8
    unsigned long EntryCount; // Size=4 Offset=16
    unsigned long ContentionCount; // Size=4 Offset=20
    unsigned long Spare[2]; // Size=8 Offset=24
} RTL_CRITICAL_SECTION_DEBUG, *PRTL_CRITICAL_SECTION_DEBUG;
typedef struct _RPC_ASYNC_STATE // Size=68
{
    unsigned int Size; // Size=4 Offset=0
    unsigned long Signature; // Size=4 Offset=4
    long Lock; // Size=4 Offset=8
    unsigned long Flags; // Size=4 Offset=12
    void * StubInfo; // Size=4 Offset=16
    void * UserInfo; // Size=4 Offset=20
    void * RuntimeInfo; // Size=4 Offset=24
    enum _RPC_ASYNC_EVENT Event; // Size=4 Offset=28
    enum _RPC_NOTIFICATION_TYPES NotificationType; // Size=4 Offset=32
    union _RPC_ASYNC_STATE::___unnamed371 u; // Size=16 Offset=36
    long Reserved[4]; // Size=16 Offset=52
} RPC_ASYNC_STATE, *PRPC_ASYNC_STATE;
typedef struct _FULL_PTR_XLAT_TABLES // Size=32
{
    struct _FULL_PTR_XLAT_TABLES::___unnamed474 RefIdToPointer; // Size=12 Offset=0
    struct _FULL_PTR_XLAT_TABLES::___unnamed475 PointerToRefId; // Size=12 Offset=12
    unsigned long NextRefId; // Size=4 Offset=24
    enum XLAT_SIDE XlatSide; // Size=4 Offset=28
} FULL_PTR_XLAT_TABLES, *PFULL_PTR_XLAT_TABLES;
typedef struct _tagSTACKFRAME // Size=116
{
    struct _tagADDRESS AddrPC; // Size=12 Offset=0
    struct _tagADDRESS AddrReturn; // Size=12 Offset=12
    struct _tagADDRESS AddrFrame; // Size=12 Offset=24
    struct _tagADDRESS AddrStack; // Size=12 Offset=36
    void * FuncTableEntry; // Size=4 Offset=48
    unsigned long Params[4]; // Size=16 Offset=52
    int Far; // Size=4 Offset=68
    int Virtual; // Size=4 Offset=72
    unsigned long Reserved[3]; // Size=12 Offset=76
    struct _KDHELP KdHelp; // Size=28 Offset=88
} tagSTACKFRAME, *PtagSTACKFRAME;
typedef class CSystemMgr // Size=1056
{
    struct sockaddr_in m_peerAddr; // Size=16 Offset=1036
    long m_lShutDownTime; // Size=4 Offset=1052
} *PCSystemMgr;
typedef struct _ACCOUNT_CHAR_INFO_ // Size=900
{
    struct _CHARACTER_INFO_ CharInfo[5]; // Size=900 Offset=0
} ACCOUNT_CHAR_INFO_, *PACCOUNT_CHAR_INFO_;
typedef class MSG_S2C_PC_APPEAR // Size=196
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    unsigned long dwPCID; // Size=4 Offset=12
    struct _CHARACTER_INFO_ CharInfo; // Size=180 Offset=16
} *PMSG_S2C_PC_APPEAR;
typedef class MSG_S2C_CHAR_LIST // Size=912
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    struct _CHARACTER_INFO_ CharInfo[5]; // Size=900 Offset=12
} *PMSG_S2C_CHAR_LIST;
typedef struct tagSTATSTG // Size=72
{
    unsigned short * pwcsName; // Size=4 Offset=0
    unsigned long type; // Size=4 Offset=4
    union _ULARGE_INTEGER cbSize; // Size=8 Offset=8
    struct _FILETIME mtime; // Size=8 Offset=16
    struct _FILETIME ctime; // Size=8 Offset=24
    struct _FILETIME atime; // Size=8 Offset=32
    unsigned long grfMode; // Size=4 Offset=40
    unsigned long grfLocksSupported; // Size=4 Offset=44
    struct _GUID clsid; // Size=16 Offset=48
    unsigned long grfStateBits; // Size=4 Offset=64
    unsigned long reserved; // Size=4 Offset=68
} *PtagSTATSTG;
typedef union _RPC_ASYNC_STATE::__unnamed // Size=16
{
    struct _RPC_ASYNC_STATE::___unnamed429::___unnamed429 APC; // Size=8 Offset=0
    struct _RPC_ASYNC_STATE::___unnamed431::___unnamed431 IOC; // Size=16 Offset=0
    struct _RPC_ASYNC_STATE::___unnamed433::___unnamed433 HWND; // Size=8 Offset=0
    void * hEvent; // Size=4 Offset=0
    void ( * NotificationRoutine)(struct _RPC_ASYNC_STATE *,void *,enum _RPC_ASYNC_EVENT); // Size=4 Offset=0
} RPC_ASYNC_STATE::__unnamed, *PRPC_ASYNC_STATE::__unnamed;
typedef struct _PROPSHEETPAGEW // Size=48
{
    unsigned long dwSize; // Size=4 Offset=0
    unsigned long dwFlags; // Size=4 Offset=4
    struct HINSTANCE__ * hInstance; // Size=4 Offset=8
    union
    {
        unsigned short * pszTemplate; // Size=4 Offset=12
        struct DLGTEMPLATE * pResource; // Size=4 Offset=12
    };
    union
    {
        struct HICON__ * hIcon; // Size=4 Offset=16
        unsigned short * pszIcon; // Size=4 Offset=16
    };
    unsigned short * pszTitle; // Size=4 Offset=20
    int ( * pfnDlgProc)(struct HWND__ *,unsigned int,unsigned int,long); // Size=4 Offset=24
    long lParam; // Size=4 Offset=28
    unsigned int ( * pfnCallback)(struct HWND__ *,unsigned int,struct _PROPSHEETPAGEW *); // Size=4 Offset=32
    unsigned int * pcRefParent; // Size=4 Offset=36
    unsigned short * pszHeaderTitle; // Size=4 Offset=40
    unsigned short * pszHeaderSubTitle; // Size=4 Offset=44
} PROPSHEETPAGEW, *PPROPSHEETPAGEW;
typedef struct _PROPSHEETPAGEA // Size=48
{
    unsigned long dwSize; // Size=4 Offset=0
    unsigned long dwFlags; // Size=4 Offset=4
    struct HINSTANCE__ * hInstance; // Size=4 Offset=8
    union
    {
        char * pszTemplate; // Size=4 Offset=12
        struct DLGTEMPLATE * pResource; // Size=4 Offset=12
    };
    union
    {
        struct HICON__ * hIcon; // Size=4 Offset=16
        char * pszIcon; // Size=4 Offset=16
    };
    char * pszTitle; // Size=4 Offset=20
    int ( * pfnDlgProc)(struct HWND__ *,unsigned int,unsigned int,long); // Size=4 Offset=24
    long lParam; // Size=4 Offset=28
    unsigned int ( * pfnCallback)(struct HWND__ *,unsigned int,struct _PROPSHEETPAGEA *); // Size=4 Offset=32
    unsigned int * pcRefParent; // Size=4 Offset=36
    char * pszHeaderTitle; // Size=4 Offset=40
    char * pszHeaderSubTitle; // Size=4 Offset=44
} PROPSHEETPAGEA, *PPROPSHEETPAGEA;
typedef struct tagWNDCLASSA // Size=40
{
    unsigned int style; // Size=4 Offset=0
    long ( * lpfnWndProc)(struct HWND__ *,unsigned int,unsigned int,long); // Size=4 Offset=4
    int cbClsExtra; // Size=4 Offset=8
    int cbWndExtra; // Size=4 Offset=12
    struct HINSTANCE__ * hInstance; // Size=4 Offset=16
    struct HICON__ * hIcon; // Size=4 Offset=20
    struct HICON__ * hCursor; // Size=4 Offset=24
    struct HBRUSH__ * hbrBackground; // Size=4 Offset=28
    char * lpszMenuName; // Size=4 Offset=32
    char * lpszClassName; // Size=4 Offset=36
} *PtagWNDCLASSA;
typedef class MSG_M2S_CHAR_UPDATE // Size=203
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    char szAccountName[21]; // Size=21 Offset=2
    struct _CHARACTER_INFO_ CharInfo; // Size=180 Offset=23
} *PMSG_M2S_CHAR_UPDATE;
typedef class ACCOUNT_INFO // Size=1048
{
    unsigned char bUpdate; // Size=1 Offset=0
    char szAccountName[21]; // Size=21 Offset=1
    unsigned char byCurrentPCIndex; // Size=1 Offset=22
    unsigned char byCmd; // Size=1 Offset=23
    unsigned char byCmdSlot; // Size=1 Offset=24
    struct _ACCOUNT_CHAR_INFO_ AccountCharInfo; // Size=900 Offset=28
    char szPasswd[21]; // Size=21 Offset=928
    char szIP[16]; // Size=16 Offset=949
    unsigned long RemainTime; // Size=4 Offset=968
    char PayMode[4]; // Size=4 Offset=972
    long PayNo; // Size=4 Offset=976
    char Reserved1[33]; // Size=33 Offset=980
    char Reserved2[33]; // Size=33 Offset=1013
} *PACCOUNT_INFO;
typedef class CFDB // Size=904
{
    struct _ACCOUNT_CHAR_INFO_ m_AccountCharInfo; // Size=900 Offset=0
    unsigned short m_wSize; // Size=2 Offset=900
} *PCFDB;
typedef union _ITEM_IN_WEAR_ // Size=20
{
    union
    {
        struct _ITEM_ item; // Size=16 Offset=0
        struct
        {
            struct _ITEM_ID_ ItemID; // Size=8 Offset=0
            union _ITEM_INFO_ ItemInfo; // Size=4 Offset=8
            union _ITEM_SERIALKEY_ ItemKey; // Size=4 Offset=12
        };
    };
    unsigned char byWearIndex; // Size=1 Offset=16
} ITEM_IN_WEAR_, *PITEM_IN_WEAR_;
typedef union _ITEM_IN_INVEN_ // Size=20
{
    union
    {
        struct _ITEM_ item; // Size=16 Offset=0
        struct
        {
            struct _ITEM_ID_ ItemID; // Size=8 Offset=0
            union _ITEM_INFO_ ItemInfo; // Size=4 Offset=8
            union _ITEM_SERIALKEY_ ItemKey; // Size=4 Offset=12
        };
    };
    unsigned char byInvenIndex; // Size=1 Offset=16
} ITEM_IN_INVEN_, *PITEM_IN_INVEN_;
typedef struct _MIDL_STUB_DESC // Size=80
{
    void * RpcInterfaceInformation; // Size=4 Offset=0
    void * ( * pfnAllocate)(unsigned int); // Size=4 Offset=4
    void ( * pfnFree)(void *); // Size=4 Offset=8
    union _MIDL_STUB_DESC::___unnamed463 IMPLICIT_HANDLE_INFO; // Size=4 Offset=12
    void ( * * apfnNdrRundownRoutines)(void *); // Size=4 Offset=16
    struct _GENERIC_BINDING_ROUTINE_PAIR * aGenericBindingRoutinePairs; // Size=4 Offset=20
    void ( * * apfnExprEval)(struct _MIDL_STUB_MESSAGE *); // Size=4 Offset=24
    struct _XMIT_ROUTINE_QUINTUPLE * aXmitQuintuple; // Size=4 Offset=28
    unsigned char * pFormatTypes; // Size=4 Offset=32
    int fCheckBounds; // Size=4 Offset=36
    unsigned long Version; // Size=4 Offset=40
    struct _MALLOC_FREE_STRUCT * pMallocFreeStruct; // Size=4 Offset=44
    long MIDLVersion; // Size=4 Offset=48
    struct _COMM_FAULT_OFFSETS * CommFaultOffsets; // Size=4 Offset=52
    struct _USER_MARSHAL_ROUTINE_QUADRUPLE * aUserMarshalQuadruple; // Size=4 Offset=56
    long Reserved1; // Size=4 Offset=60
    long Reserved2; // Size=4 Offset=64
    long Reserved3; // Size=4 Offset=68
    long Reserved4; // Size=4 Offset=72
    long Reserved5; // Size=4 Offset=76
} MIDL_STUB_DESC, *PMIDL_STUB_DESC;
typedef struct _MIDL_STUB_MESSAGE // Size=180
{
    struct _RPC_MESSAGE * RpcMsg; // Size=4 Offset=0
    unsigned char * Buffer; // Size=4 Offset=4
    unsigned char * BufferStart; // Size=4 Offset=8
    unsigned char * BufferEnd; // Size=4 Offset=12
    unsigned char * BufferMark; // Size=4 Offset=16
    unsigned long BufferLength; // Size=4 Offset=20
    unsigned long MemorySize; // Size=4 Offset=24
    unsigned char * Memory; // Size=4 Offset=28
    int IsClient; // Size=4 Offset=32
    int ReuseBuffer; // Size=4 Offset=36
    unsigned char * AllocAllNodesMemory; // Size=4 Offset=40
    unsigned char * AllocAllNodesMemoryEnd; // Size=4 Offset=44
    int IgnoreEmbeddedPointers; // Size=4 Offset=48
    unsigned char * PointerBufferMark; // Size=4 Offset=52
    unsigned char fBufferValid; // Size=1 Offset=56
    unsigned char Unused; // Size=1 Offset=57
    unsigned long MaxCount; // Size=4 Offset=60
    unsigned long Offset; // Size=4 Offset=64
    unsigned long ActualCount; // Size=4 Offset=68
    void * ( * pfnAllocate)(unsigned int); // Size=4 Offset=72
    void ( * pfnFree)(void *); // Size=4 Offset=76
    unsigned char * StackTop; // Size=4 Offset=80
    unsigned char * pPresentedType; // Size=4 Offset=84
    unsigned char * pTransmitType; // Size=4 Offset=88
    void * SavedHandle; // Size=4 Offset=92
    struct _MIDL_STUB_DESC * StubDesc; // Size=4 Offset=96
    struct _FULL_PTR_XLAT_TABLES * FullPtrXlatTables; // Size=4 Offset=100
    unsigned long FullPtrRefId; // Size=4 Offset=104
    int fCheckBounds; // Size=4 Offset=108
    struct
    {
        int fInDontFree: 1; // Size=4 Offset=112 BitOffset=0 BitCount=1
        int fDontCallFreeInst: 1; // Size=4 Offset=112 BitOffset=1 BitCount=1
        int fInOnlyParam: 1; // Size=4 Offset=112 BitOffset=2 BitCount=1
        int fHasReturn: 1; // Size=4 Offset=112 BitOffset=3 BitCount=1
    };
    unsigned long dwDestContext; // Size=4 Offset=116
    void * pvDestContext; // Size=4 Offset=120
    struct ___unnamed390 * * SavedContextHandles; // Size=4 Offset=124
    long ParamNumber; // Size=4 Offset=128
    struct IRpcChannelBuffer * pRpcChannelBuffer; // Size=4 Offset=132
    struct ARRAY_INFO * pArrayInfo; // Size=4 Offset=136
    unsigned long * SizePtrCountArray; // Size=4 Offset=140
    unsigned long * SizePtrOffsetArray; // Size=4 Offset=144
    unsigned long * SizePtrLengthArray; // Size=4 Offset=148
    void * pArgQueue; // Size=4 Offset=152
    unsigned long dwStubPhase; // Size=4 Offset=156
    struct _NDR_PIPE_DESC * pPipeDesc; // Size=4 Offset=160
    struct _NDR_ASYNC_MESSAGE * pAsyncMsg; // Size=4 Offset=164
    unsigned long Reserved[3]; // Size=12 Offset=168
} MIDL_STUB_MESSAGE, *PMIDL_STUB_MESSAGE;
typedef struct _PCDATA_ // Size=868
{
    char szPCName[13]; // Size=13 Offset=0
    unsigned char byType; // Size=1 Offset=13
    unsigned short wLevel; // Size=2 Offset=14
    unsigned long dwExp; // Size=4 Offset=16
    unsigned short wStr; // Size=2 Offset=20
    unsigned short wMagic; // Size=2 Offset=22
    unsigned short wDex; // Size=2 Offset=24
    unsigned short wVit; // Size=2 Offset=26
    unsigned short wMana; // Size=2 Offset=28
    unsigned short wPoint; // Size=2 Offset=30
    unsigned short wHP; // Size=2 Offset=32
    unsigned short wMp; // Size=2 Offset=34
    unsigned short wStoredHp; // Size=2 Offset=36
    unsigned short wStoredMp; // Size=2 Offset=38
    unsigned short wMapIndex; // Size=2 Offset=40
    unsigned long dwCellIndex; // Size=4 Offset=44
    struct _SKILL_ SkillList; // Size=8 Offset=48
    unsigned char byPKCount; // Size=1 Offset=56
    unsigned short wRTime; // Size=2 Offset=58
    struct _SOCIALINFO_ SInfo; // Size=4 Offset=60
    unsigned long dwMoney; // Size=4 Offset=64
    union _ITEM_IN_WEAR_ WearList[10]; // Size=200 Offset=68
    union _ITEM_IN_INVEN_ HaveList[30]; // Size=600 Offset=268
} PCDATA_, *PPCDATA_;
typedef class MSG_S2C_WORLD_LOGIN // Size=880
{
    class MSG_S2C_HEADER MsgHeader; // Size=12 Offset=0
    struct _PCDATA_ PCData; // Size=868 Offset=12
} *PMSG_S2C_WORLD_LOGIN;
typedef class MSG_M2S_WORLD_LOGIN // Size=989
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    struct _PCDATA_ PCData; // Size=868 Offset=6
    char szPasswd[21]; // Size=21 Offset=874
    char szIP[16]; // Size=16 Offset=895
    unsigned long RemainTime; // Size=4 Offset=911
    char PayMode[4]; // Size=4 Offset=915
    long PayNo; // Size=4 Offset=919
    char Reserved1[33]; // Size=33 Offset=923
    char Reserved2[33]; // Size=33 Offset=956
} *PMSG_M2S_WORLD_LOGIN;
typedef class MSG_S2M_CHAR_LOGOUT // Size=874
{
    class MSG_S2S_HEADER MsgHeader; // Size=2 Offset=0
    unsigned long dwPCID; // Size=4 Offset=2
    struct _PCDATA_ PCData; // Size=868 Offset=6
} *PMSG_S2M_CHAR_LOGOUT;
typedef struct tagPROPVARIANT // Size=16
{
    unsigned short vt; // Size=2 Offset=0
    unsigned short wReserved1; // Size=2 Offset=2
    unsigned short wReserved2; // Size=2 Offset=4
    unsigned short wReserved3; // Size=2 Offset=6
    union
    {
        unsigned char bVal; // Size=1 Offset=8
        short iVal; // Size=2 Offset=8
        unsigned short uiVal; // Size=2 Offset=8
        short boolVal; // Size=2 Offset=8
        long lVal; // Size=4 Offset=8
        unsigned long ulVal; // Size=4 Offset=8
        float fltVal; // Size=4 Offset=8
        long scode; // Size=4 Offset=8
        union _LARGE_INTEGER hVal; // Size=8 Offset=8
        union _ULARGE_INTEGER uhVal; // Size=8 Offset=8
        double dblVal; // Size=8 Offset=8
        union tagCY cyVal; // Size=8 Offset=8
        double date; // Size=8 Offset=8
        struct _FILETIME filetime; // Size=8 Offset=8
        struct _GUID * puuid; // Size=4 Offset=8
        struct tagBLOB blob; // Size=8 Offset=8
        struct tagCLIPDATA * pclipdata; // Size=4 Offset=8
        struct IStream * pStream; // Size=4 Offset=8
        struct IStorage * pStorage; // Size=4 Offset=8
        unsigned short * bstrVal; // Size=4 Offset=8
        struct tagBSTRBLOB bstrblobVal; // Size=8 Offset=8
        char * pszVal; // Size=4 Offset=8
        unsigned short * pwszVal; // Size=4 Offset=8
        struct tagCAUB caub; // Size=8 Offset=8
        struct tagCAI cai; // Size=8 Offset=8
        struct tagCAUI caui; // Size=8 Offset=8
        struct tagCABOOL cabool; // Size=8 Offset=8
        struct tagCAL cal; // Size=8 Offset=8
        struct tagCAUL caul; // Size=8 Offset=8
        struct tagCAFLT caflt; // Size=8 Offset=8
        struct tagCASCODE cascode; // Size=8 Offset=8
        struct tagCAH cah; // Size=8 Offset=8
        struct tagCAUH cauh; // Size=8 Offset=8
        struct tagCADBL cadbl; // Size=8 Offset=8
        struct tagCACY cacy; // Size=8 Offset=8
        struct tagCADATE cadate; // Size=8 Offset=8
        struct tagCAFILETIME cafiletime; // Size=8 Offset=8
        struct tagCACLSID cauuid; // Size=8 Offset=8
        struct tagCACLIPDATA caclipdata; // Size=8 Offset=8
        struct tagCABSTR cabstr; // Size=8 Offset=8
        struct tagCABSTRBLOB cabstrblob; // Size=8 Offset=8
        struct tagCALPSTR calpstr; // Size=8 Offset=8
        struct tagCALPWSTR calpwstr; // Size=8 Offset=8
        struct tagCAPROPVARIANT capropvar; // Size=8 Offset=8
    };
} *PtagPROPVARIANT;

#endif
